### PR TITLE
james and long add docstring

### PR DESCRIPTION
**Pull request by gzz0707**
Hi Pavol,

Long and I worked on the doc string for the space group file, and we thought they're ready for your review. Please feel free to take a look and let either of us know how this should be further modified. Thanks a lot.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Hi @gzz0707 and @dragonyanglong.  As a convention the source files in diffpy repositories use UNIX line format, i.e., the lines should end with a single `\n` character instead of `\r\n` pair.  (The only exception are the `.bat` files or test data).

Please, convert from DOS to UNIX line format and consider setting your text editor to use UNIX line ends by default.  Another option is to setup the `core.eol` and `core.safecrlf` options in your git config (see the git-config documentation).  Also please remove any trailing blanks.  Make sure there are no issues reported from

```
git diff --check python3...HEAD
```

When done, please squash the new commits into a single one and force-push your branch.  This will ensure the output from `git blame` and `git log -p` will be useful in the future as currently it appears your commit has changed every line in spacegroupmod.py.

Here is an outline what to do:
```
git checkout py3-sg-docs
# ... convert to unix format, fix trailing spaces
git commit --fixup=HEAD
# save current commit in a temporary backup branch
git branch xbackup-sg-docs HEAD
# rebase on the branch-off commit e186ab6f in the python3 branch
# you can find it by using "git merge-base HEAD python3" or by looking
# at commit graph in "gitk --branches"
git rebase -i --autosquash e186ab6f
# assuming remote "james" is set to "https://github.com/gzz0707/diffpy.structure.git"
git push james --force-with-lease py3-sg-docs:py3-sg-docs
```

The final force-push also updates this PR, so afterwards it should show just one commit with correct line format.

**Comment by sbillinge** [comment]
force pushes are VERY DANGEROUS and to be avoided if possible.  I
understand why Pavol wants this to be fixed, the line-end issue ruins
everything in diff, but please could I ask @pavoljuhas to be present, at
least on a Google Hangout, when this is done so that no bad things happen.

@gzz0707 <https://github.com/gzz0707> and @dragonyanglong
<https://github.com/dragonyanglong> I think it is time for you to download
and start to use a better python editing environment/IDE such as PyCharm or
Sublime which can be set up to handle the line-ends issue automatically.

S

**Comment by pavoljuhas** [comment]
> force pushes are VERY DANGEROUS and to be avoided if possible.  I
understand why Pavol wants this to be fixed, the line-end issue ruins
everything in diff, but please could I ask @pavoljuhas to be present, at
least on a Google Hangout, when this is done so that no bad things happen.

Sure, I'd be glad to help with that.

For a peace of mind, I configured the branches in the main diffpy/diffpy.structure repository to prohibit force-pushes, so there should be no danger there.  On the other hand, branches in developer's own
fork could be considered as his own sandbox.  Unless somebody else uses them to start new work, there is no harm in deleting or changing them in any way the owner likes.

As a safety measure, force pushes should be done only with `--force-with-lease` option (DO NOT use `--force`), which let's them pass only if the replaced commit in target repo is the same as what was last fetched from there.  This ensures the target branch has no new commits added in meantime by someone else.

Also, always test force pushes with the `--dry-run` option first to verify they would go as intended.

**Comment by pavoljuhas** [comment]
@gzz0707 - please review my updates to this PR in https://github.com/diffpy/diffpy.structure/pull/17/files/4f23188c8963330d269c4a30da7587749ea6110d..19e47a9b7cd409a654101c7c07f9259092486c2f
Let me know if you have updates / comments or if this is OK to merge.  Thank you.

**Comment by gzz0707** [comment]
@pavoljuhas Thanks Pavol. I have finished reading the new doc strings you wrote and it looks very nice. Please feel free to push it.

**Pull request merged**
