### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by Tieqiong**

### CODE REVIEW

**Comment by sbillinge** [comment]
@Tieqiong why is there a force push?  I don't really want to merge anything with force pushes in.

**Comment by Tieqiong** [comment]
> @Tieqiong why is there a force push? I don't really want to merge anything with force pushes in.

To replace the ci-bot changes

**Comment by sbillinge** [comment]
Also, please confirm, are you running pre-commit locally?  Then pre-commit.ci shouldn't have to make commits

**Comment by Tieqiong** [comment]
> Also, please confirm, are you running pre-commit locally? Then pre-commit.ci shouldn't have to make commits

Sure I'll do it locally

**Comment by sbillinge** [comment]
> > Also, please confirm, are you running pre-commit locally? Then pre-commit.ci shouldn't have to make commits
> 
> Sure I'll do it locally

please make sure that you run `pre-commit install` on all your repositories.

**Comment by sbillinge** [comment]
> > @Tieqiong why is there a force push? I don't really want to merge anything with force pushes in.
> 
> To replace the ci-bot changes

Let's close this and redo it without force pushes.    Please don't force push.

**Pull request closed without merging**
