### PR TITLE
cookie release 

### PR DESCRIPTION
**Pull request by Tieqiong**

### CODE REVIEW

**Comment by Tieqiong** [comment]
@sbillinge 

I made two issues #64 and #65 that we might want to fix. For #64 we want to make sure the testings are working (related to [a399f18](https://github.com/diffpy/diffpy.structure/pull/63/commits/a399f18d337ff0cc1b43526eb29c6b967d523aff) and [15e0c07](https://github.com/diffpy/diffpy.structure/pull/63/commits/15e0c079bc4edfcae38aee724127a8c64a221137) (only change header). might related to [7452562](https://github.com/diffpy/diffpy.structure/pull/63/commits/7452562443d405b711a610e1288ef37f9e4ef21f)). For #65 I got warnings while making html, which are related to the docstrings. I think this might also be relating to the failures in CI. 

Another important question for this package is the licenses. I **changed the file type from `.txt` to `.rst`** and **added 2024 Columbia in `license.rst` and `license_danse.rst`** while keeping all other the same (type of licenses and `license_pymmlib.rst`). 

Other potential problems:
- devutils (do we need it?)
- requirements (add requirements?)
- diffpy/Structure.py (do we need it?)
- headers for python files
- keywords (is 'crystal structure data storage CIF PDB' one keyword?)
- update `MANIFEST.in` and doc related links for license
- Codecov has been deactivated
- No GitHub action page
-

**Comment by sbillinge** [comment]
@Tieqiong I am merging this so we can move forward.

the most important next step is to get the tests working with pytest, and then to set up the github workflows so we are running tests for the CI.  

Let's try and do that on a new PR.   Please also make a news item to cover this  cookie-release activity (as well as news items for each of the subsequent PRs.  In general we expect one news item per PR.

**Comment by Tieqiong** [comment]
> @Tieqiong I am merging this so we can move forward.
> 
> the most important next step is to get the tests working with pytest, and then to set up the github workflows so we are running tests for the CI.
> 
> Let's try and do that on a new PR. Please also make a news item to cover this cookie-release activity (as well as news items for each of the subsequent PRs. In general we expect one news item per PR.

@sbillinge 
I'm trying to get the tests working, and I referred to `diffpy.utils` and `diffpy.pdfmorph`. Don't know exactly why but it seems like the testing (I did `python -m {{ name }}.tests`) works for `diffpy.utils` but not `diffpy.pdfmorph`. The error is `No module named diffpy.pdfmorph.tests` and it's also happening for `diffpy.labpdfproc` and `diffpy.structure`. I guess the `__init __` inside tests folder is not properly set up for the cookiecutter. I'll need to learn and try around with it.

I also notice the unittest to pytest thing is not a problem now, as we have a conftest that should be able to do the fixture. I'll make sure it's working properly after fixing the unittest.

**Comment by Sparks29032** [comment]
How are you installing the modules before testing?

**Comment by Tieqiong** [comment]
> How are you installing the modules before testing?

By pip install . into the env

**Comment by Tieqiong** [comment]
I install the package by pip install .
I'm not sure how to install the modules?

**Pull request merged**
